version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  frontend: 
    container_name: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend